from oracle.trace import summarize_vcd

# Condensed from a real runs/kitest_weak_prove_*/job/engine_0/trace_induct.vcd
# (Yosys-SMTBMC output): same header/var/scope/value-change syntax, two
# steps instead of twenty-two.
CTI_VCD = """\
$version Generated by Yosys-SMTBMC $end
$timescale 1ns $end
$var integer 32 t smt_step $end
$var event 1 ! smt_clock $end
$scope module kitest $end
$var wire 1 n0 i_ce $end
$var wire 1 n1 i_clk $end
$var wire 1 n2 i_in $end
$var wire 1 n3 i_reset $end
$var wire 1 n4 o_bit $end
$var wire 32 n5 sa $end
$var wire 32 n6 sb $end
$upscope $end
$enddefinitions $end
#0
1!
b00000000000000000000000000000000 t
b1 n1
b0 n0
b0 n2
b0 n3
b0 n4
b00000000000000000000000000000000 n5
b01000000000000000000000000000000 n6
#5
b0 n1
#10
1!
b00000000000000000000000000010101 t
b1 n1
b1 n0
b0 n2
b0 n3
b1 n4
b00000000000000000000000000000000 n5
b10000000000000000000000000000000 n6
"""


def test_start_state_extracted():
    text = summarize_vcd_text()
    assert "step 0" in text
    assert "sa = 32'h00000000" in text
    assert "sb = 32'h40000000" in text


def test_failure_state_extracted_with_step_number():
    text = summarize_vcd_text()
    assert "step 21" in text          # final smt_step = 0b10101
    assert "sb = 32'h80000000" in text
    assert "o_bit = 1" in text


def test_bookkeeping_vars_excluded():
    text = summarize_vcd_text()
    assert "smt_step" not in text
    assert "smt_clock" not in text


def test_malformed_vcd_reports_not_raises(tmp_path):
    p = tmp_path / "junk.vcd"
    p.write_text("this is not a vcd file")
    text = summarize_vcd(p)
    assert "no signal data" in text


def summarize_vcd_text():
    import tempfile
    from pathlib import Path
    with tempfile.TemporaryDirectory() as td:
        p = Path(td) / "trace_induct.vcd"
        p.write_text(CTI_VCD)
        return summarize_vcd(p)
