from oracle.trace import summarize_vcd

# Condensed from a real runs/kitest_weak_prove_*/job/engine_0/trace_induct.vcd
# (Yosys-SMTBMC output): same header/var/scope/value-change syntax, two
# steps instead of twenty-two.
CTI_VCD = """\
$version Generated by Yosys-SMTBMC $end
$timescale 1ns $end
$var integer 32 t smt_step $end
$var event 1 ! smt_clock $end
$scope module kitest $end
$var wire 1 n0 i_ce $end
$var wire 1 n1 i_clk $end
$var wire 1 n2 i_in $end
$var wire 1 n3 i_reset $end
$var wire 1 n4 o_bit $end
$var wire 32 n5 sa $end
$var wire 32 n6 sb $end
$upscope $end
$enddefinitions $end
#0
1!
b00000000000000000000000000000000 t
b1 n1
b0 n0
b0 n2
b0 n3
b0 n4
b00000000000000000000000000000000 n5
b01000000000000000000000000000000 n6
#5
b0 n1
#10
1!
b00000000000000000000000000010101 t
b1 n1
b1 n0
b0 n2
b0 n3
b1 n4
b00000000000000000000000000000000 n5
b10000000000000000000000000000000 n6
"""


def test_start_state_extracted():
    text = summarize_vcd_text()
    assert "step 0" in text
    assert "sa = 32'h00000000" in text
    assert "sb = 32'h40000000" in text


def test_failure_state_extracted_with_step_number():
    text = summarize_vcd_text()
    assert "step 21" in text          # final smt_step = 0b10101
    assert "sb = 32'h80000000" in text
    assert "o_bit = 1" in text


def test_bookkeeping_vars_excluded():
    text = summarize_vcd_text()
    assert "smt_step" not in text
    assert "smt_clock" not in text


def test_malformed_vcd_reports_not_raises(tmp_path):
    p = tmp_path / "junk.vcd"
    p.write_text("this is not a vcd file")
    text = summarize_vcd(p)
    assert "no signal data" in text


def summarize_vcd_text():
    import tempfile
    from pathlib import Path
    with tempfile.TemporaryDirectory() as td:
        p = Path(td) / "trace_induct.vcd"
        p.write_text(CTI_VCD)
        return summarize_vcd(p)


# --- bigger designs (8 Oct 2026): the tool's made-up signals filled repair
# notes (2,100 anyseq_auto_setundef_* names across 4,000 saved traces) ---

NOISY_VCD = CTI_VCD.replace(
    "$var wire 32 n6 sb $end\n",
    "$var wire 32 n6 sb $end\n"
    "$var wire 8 n7 anyseq_auto_setundef_cc_550_execute_157 $end\n"
    "$var wire 1 n8 \\$auto$proc_rom.cc:155:do_switch$13<0> $end\n"
    "$var wire 8 n9 anyinit_procdff_72 $end\n").replace(
    "b0 n4\n", "b0 n4\nb00000001 n7\nb1 n8\nb00000011 n9\n")


def _summary(text, **kw):
    import tempfile
    from pathlib import Path
    with tempfile.TemporaryDirectory() as td:
        p = Path(td) / "trace_induct.vcd"
        p.write_text(text)
        return summarize_vcd(p, **kw)


def test_tool_made_signals_are_left_out():
    text = _summary(NOISY_VCD)
    assert "anyseq_auto_setundef" not in text
    assert "$auto$" not in text
    assert "sa = 32'h00000000" in text


def test_the_hidden_past_register_is_kept():
    # anyinit_procdff_* is the register behind $past: real state, and the
    # value a model must see to understand a $past counterexample
    assert "anyinit_procdff_72 = 8'h03" in _summary(NOISY_VCD)


def test_a_reached_cover_is_not_called_a_failure():
    text = _summary(CTI_VCD, final_label="cover reached")
    assert "At cover reached (step 21)" in text
    assert "failure" not in text
